name: Publish GoDoc to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21'

      - name: Generate GoDoc HTML
        run: |
          go get -v golang.org/x/tools/cmd/godoc
          godoc -http=:6060 &
          sleep 5
          wget -r -k -p -P docs http://localhost:6060/pkg/im2dhistgo.go

      - name: Checkout Documentation Branch
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'gh_pages_repo'

      - name: Commit and Push Changes
        run: |
          cd gh_pages_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
              echo "No changes to commit. Skipping git push."
          else
              # Commit and push if there are staged changes
              git commit -m "Update documentation"
              git push origin gh-pages
          fi
